Repository fizzi01/MisureRel, pull requests merged in 2023-06, with the labels that each got.

#28 Aggiornato e migliorato il tutorial (Che senno Ludovico piange)
  README.md
Labels: enhancement

#29 Sistemate gli headers delle tabelle
  Relazione/chapters/Prova2.tex
  Relazione/main.tex
Labels: enhancement, fix

#31 sistemato indice prova 2
  Relazione/chapters/seconda_prova.tex
  Relazione/main.tex
Labels: fix

#63 GIGAFIX
  Relazione/chapters/lcr.tex
  Relazione/chapters/mult.tex
  Relazione/chapters/mult_port.tex
  Relazione/chapters/prima_prova.tex
  Relazione/chapters/terza_prova.tex
Labels: GIGA FIX

#75 Fix e sistemazioni varie Complete
  .github/workflows/check.yml
  Relazione/chapters/prima_prova.tex
  Relazione/chapters/seconda_prova.tex
  Relazione/chapters/terza_prova.tex
  Relazione/main.tex
Labels: invalid

#79 Prima prova LCR
  Relazione/chapters/prima_prova.tex
  Relazione/media/LCR_meter.png
  Relazione/media/diagramma_conversione_Cp.png
  Relazione/media/pannello_frontale_LCR.png
Labels: bug

#85 Bode
  Relazione/chapters/prima_prova.tex
  Relazione/chapters/terza_prova.tex
  Relazione/main.tex
  Relazione/media/bode/bode_adb_20logOmega.txt
  Relazione/media/bode/bode_adb_20logf.txt
  Relazione/media/bode/bode_adb_logOmega.txt
  Relazione/media/bode/bode_adb_logf.txt
  Relazione/media/bode/bode_adb_logf_u.txt
Labels: enhancement

#101 Miglioramenti grafici e notazionali
  Relazione/chapters/prima_prova.tex
  Relazione/chapters/seconda_prova.tex
Labels: enhancement, fix
